name: mujoco_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - attrs=24.3.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cachecontrol=0.12.11
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - cleo=2.1.0
  - crashtest=0.4.1
  - cryptography=44.0.1
  - dbus=1.13.18
  - distlib=0.3.8
  - dulwich=0.21.3
  - expat=2.7.1
  - filelock=3.17.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - html5lib=1.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - intel-openmp=2023.1.0
  - jaraco.classes=3.2.1
  - jeepney=0.7.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - keyring=23.13.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - lockfile=0.12.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - more-itertools=10.3.0
  - msgpack-python=1.0.3
  - ncurses=6.4
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openssl=3.0.16
  - packaging=24.2
  - pcre2=10.42
  - pexpect=4.8.0
  - pip=25.1
  - pkginfo=1.12.0
  - platformdirs=2.5.2
  - poetry=1.4.0
  - poetry-core=1.5.1
  - poetry-plugin-export=1.3.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pyopenssl=25.0.0
  - pyproject_hooks=1.0.0
  - pysocks=1.7.1
  - python=3.10.12
  - python-build=0.10.0
  - python-installer=0.6.0
  - rapidfuzz=3.12.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - requests-toolbelt=0.9.1
  - rpds-py=0.22.3
  - secretstorage=3.3.1
  - setuptools=78.1.1
  - shellingham=1.5.0
  - six=1.17.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tomlkit=0.13.2
  - trove-classifiers=2024.10.14
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=1.26.19
  - virtualenv=20.17.1
  - webencodings=0.5.1
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zipp=3.21.0
  - zlib=1.2.13
